### PR TITLE
Fix remaining examples that are using deprecated local call syntax

### PR DESCRIPTION
**Pull request by chrislee973**
Fixes the few straggling cases in the examples that were still referencing the deprecated f(...) syntax of calling a function locally.

### Type of Change

- [ ] New Example
- [ X] Example updates (Bug fixes, new features, etc.)
- [ ] Other (changes to the codebase, but not to examples)

Closes #560

### CODE REVIEW

**Review by erikbern — APPROVED** [review]
Thanks!!

**Comment by erikbern** [comment]
Something is weird with Github since it's impossible to merge this... not sure what happened

**Comment by ekzhang** [comment]
I added a requirement to pass Ruff / Black in CI before merging PRs (both take <10 seconds to run) — since a couple recent changes were merged while failing CI jobs. But it looks like it's not running for external contributors.

**Comment by ekzhang** [comment]
Okay, let's try again!

**Comment by ekzhang** [comment]
Closes #560

**Pull request merged**
