### PR TITLE
Capitalize A10G correctly

### PR DESCRIPTION
**Pull request by ekzhang**
https://www.nvidia.com/en-gb/data-center/products/a10-gpu/

### CODE REVIEW

**Comment by jkukul** [comment]
@ekzhang Could it be that this actually broke something? 

The example dreambooth app seems to be broken:
https://modal-labs-example-dreambooth-app-fastapi-app.modal.run/

I can reproduce the error when deploying the app myself, but when I change it back to `gpu="A10g"` it works.

**Comment by erikbern** [comment]
Thanks for mentioning @jkukul  – we'll take a look!

**Comment by jkukul** [comment]
After more testing, I think this PR  unrelated. The app breaks for me with both `A10G` and `A10g`.  In both cases, the contents of the volume are not attached to `/model` directory. 

It consistently works with `A100`, so the same gpu that was used for training the model.

**Comment by erikbern** [comment]
It sounds like what you're running into @jkukul is that A100s run in a different cloud provider than A10G, so the shared volume content will be different based on that. It's pretty confusing and we hope to fix this soon!

**Pull request merged**
