### PR TITLE
pulling in flux improvements from ShariqM fork

### PR DESCRIPTION
**Pull request by charlesfrye**
making this PR so we can run our CI on it

### CODE REVIEW

**Comment by charlesfrye** [comment]
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-03dcf62.modal.run

**Comment by charlesfrye** [comment]
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-87c42e7.modal.run

**Comment by charlesfrye** [comment]
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-8b40476.modal.run

**Comment by charlesfrye** [comment]
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-097e0cc.modal.run

**Comment by ShariqM** [comment]
looking good!

**Pull request merged**
