### PR TITLE
Do not merge: Test building examples on 2024.10 image builder

### PR DESCRIPTION
**Pull request by mwaskom**

### CODE REVIEW

**Comment by charlesfrye** [comment]
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-e51382d.modal.run

**Comment by charlesfrye** [comment]
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-e0278b0.modal.run

**Comment by charlesfrye** [comment]
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-48f0a54.modal.run

**Comment by mwaskom** [comment]
Remaining failures here appear unrelated to the image builder version (timeouts, what appears to be some dependency drift) so considering these compatible with 2024.10.

**Pull request closed without merging**
