### PR TITLE
Bring back codelangchain

### PR DESCRIPTION
**Pull request by charlesfrye**
This PR resurrects the `codelangchain` example and tries to make it more testable in CI.

It also reworks the example as a Python coding agent, since Python's docs and behavior are more stable than LangChain's.

It is in draft because it needs some more work to make it a good fit for the docs site, but I wanted to share the WIP state.

Some TODOs:

1. The documentation is currently in a README, rather than written as literate programming. That'll be tricky because the `codelangchain` file contains just the LangServe server, but the interesting code for sandboxes is in `src/sandbox.py` and the interesting code for the "agent" is spread across multiple files in `src`.
2. The Python example isn't incredibly compelling, since base models already know a lot of Python. We could always update to the bleeding edge Python so that the "tell me something new about Python" feature is both interesting to users and differentiated from base model capabilities. But maybe we want to use some slightly slower-moving data science library here? Like numpy, pandas, polars, or transformers? And maybe we want to give the agent a GPU, to show off that feature of Modal Sandboxes?
3. The Sandboxes are not stateful and just use the "create and execute terminating command, then read stdout/stderr" API that was available at the time this example was first written. Can we do something cooler with the new APIs?

### Type of Change

- [ ] New example
- [x] Example updates (Bug fixes, new features, etc.)
- [ ] Other (changes to the codebase, but not to examples)

### CODE REVIEW

**Comment by charlesfrye** [comment]
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-c72f99f.modal.run

**Comment by pawalt** [comment]
my changes:
1. `agent.py` is now literate programmed
2. we're now using transformers with a gpu
3. exec is now used which makes this a lot faster

**Comment by charlesfrye** [comment]
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-dfda8a2.modal.run

**Comment by charlesfrye** [comment]
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-6d47652.modal.run

**Comment by charlesfrye** [comment]
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-0df9287.modal.run

**Comment by charlesfrye** [comment]
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-02373ae.modal.run

**Comment by charlesfrye** [comment]
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-d2ec677.modal.run

**Comment by charlesfrye** [comment]
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-a6831d2.modal.run

**Comment by charlesfrye** [comment]
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-5a686dc.modal.run

**Pull request merged**
