### PR TITLE
adds an action to preview docs

### PR DESCRIPTION
**Pull request by charlesfrye**

### CODE REVIEW

**Comment by charlesfrye** [comment]
The expected outcome of the checks on 90f43b7 is that the Preview Docs action will fail at the step where the docs are built.

This is a "positive control" -- testing that we catch a known issue.

**Comment by charlesfrye** [comment]
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-d2a8a5c.modal.run

**Review by ekzhang — APPROVED** [review]
Perfect, thank you!

**Comment by charlesfrye** [comment]
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-58233a7.modal.run

**Pull request merged**
