### PR TITLE
10k -> 100k checkboxes

### PR DESCRIPTION
**Pull request by charlesfrye**

### CODE REVIEW

**Comment by charlesfrye** [comment]
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-38d49a9.modal.run

**Comment by erik-dunteman** [comment]
@charlesfrye FYI
- renamed files to remove redundancy (made sure the `modal run` docs reflect changes)
- fixed ruff
- redrew image

**Comment by charlesfrye** [comment]
Something went wrong with the preview deployment.

**Comment by erik-dunteman** [comment]
> Something went wrong with the preview deployment.

I'm sorry bot Charles! Will investigate

**Comment by charlesfrye** [comment]
🚀 The docs preview is ready! Check it out here:     https://modal-labs-examples--frontend-preview-94aec21.modal.run

**Pull request merged**
